# Dorothea computes a KDST after selecting PMAPS according to an S12 selector.

include('$ICDIR/config/s12_selector.conf')

# override the default input/output files:
# files_in = '/scratch/marian/ic-course/data/IN_FILE.hypathia.h5'
files_in = '/data/marian/IC/hypathia/20250624_Next100_1Kev_ELoff_Kr_*[0-9].hypathia.h5'
# files_in = '/scratch/marian/ic-course/data/20250624_Next100_1Kev_ELoff_Kr_*_PMTs.hypathia.h5'
file_out = '/scratch/marian/IC/outputs/OUT_FILE.dorothea.h5'
compression = 'ZLIB4'

# run number 0 is for MC
run_number = 0
# detector_db = 'next100fibers'
detector_db = 'next100'

# How frequently to print events
print_mod = 1

# Dorothea uses s12 selector parameters
# and can re-write some of them
# for example s2 parameters are re-written here

event_range = all

drift_v     =      1    * mm / mus
s1_nmin     =      1
s1_nmax     =      1
s1_emin     =      0    * pes
s1_emax     =    500    * pes
s1_wmin     =    100    * ns
s1_wmax     =    700    * ns
s1_hmin     =      0    * pes
s1_hmax     =     30    * pes
s1_ethr     =      0    * pes
s2_nmin     =      1
s2_nmax     =      2
s2_emin     =    1e3    * pes
s2_emax     =    1e8    * pes
s2_wmin     =      1    * mus
s2_wmax     =    100    * mus
s2_hmin     =    100    * pes
s2_hmax     =    1e5    * pes
s2_ethr     =      1    * pes
s2_nsipmmin =      2
s2_nsipmmax =   1000

global_reco_algo = corona
global_reco_params = dict(
  Qthr=4*pes,
  Qlm =4*pes,
  lm_radius=1,
  new_lm_radius=2*np.sqrt(2)*15.55 + 0.1,
  msipm=1,
  consider_masked=False,
)

sipm_charge_type = raw
